# docker-compose.yaml

version: "2"

services:
  app:
    image: node_nsolid
    container_name: nsolid.app
    ports:
      - 9999:9999 # Port your application exposes
    volumes:
      - ./server.js:/server.js
    environment:
      - NSOLID_APPNAME=app
      - NSOLID_COMMAND=console:9001
      - NSOLID_DATA=console:9002
      - NSOLID_BULK=console:9003
    networks:
      - nsolid

  console:
    image: nodesource/nsolid-console
    container_name: nsolid.console
    ports:
      - 9001:9001
      - 6753:6753

    networks:
      - nsolid

networks:
  nsolid:
